//GENERAL
export const CONNECTED = 'CONNECTED';
export const INCOMING_MESSAGE = 'INCOMING_MESSAGE';
export const INCOMING_MESSAGE_SEEN = 'INCOMING_MESSAGE_SEEN';


//USER
export const IDENTIFY_USER = 'IDENTIFY_USER';
export const IDENTIFYING_USER_SUCCEEDED = 'IDENTIFYING_USER_SUCCEEDED';
export const IDENTIFYING_USER_FAILED = 'IDENTIFYING_USER_FAILED';

//GUEST
export const IDENTIFY_GUEST = 'IDENTIFY_GUEST';
export const IDENTIFYING_GUEST_SUCCEEDED = 'IDENTIFYING_GUEST_SUCCEEDED';
export const IDENTIFYING_GUEST_FAILED = 'IDENTIFYING_GUEST_FAILED';
export const CHAT_LICENSE_ERROR = 'CHAT_LICENSE_ERROR';
export const GUEST_COOKIE_SET = 'GUEST_COOKIE_SET';
export const GUEST_MESSAGES_GET = 'GUEST_MESSAGES_GET';  
export const GUEST_MESSAGES_SEND = 'GUEST_MESSAGES_SEND';  