//GENERAL
export const CONNECTED = 'CONNECTED';
export const INCOMING_MESSAGE = 'INCOMING_MESSAGE';


//USER
export const IDENTIFY_USER = 'IDENTIFY_USER';
export const IDENTIFYING_USER_SUCCEEDED = 'IDENTIFYING_USER_SUCCEEDED';
export const IDENTIFYING_USER_FAILED = 'IDENTIFYING_USER_FAILED';

//GUEST
export const IDENTIFY_GUEST = 'IDENTIFY_GUEST';
export const IDENTIFYING_GUEST_SUCCEEDED = 'IDENTIFYING_GUEST_SUCCEEDED';
export const IDENTIFYING_GUEST_FAILED = 'IDENTIFYING_GUEST_FAILED';
export const CHAT_LICENSE_ERROR = 'CHAT_LICENSE_ERROR';